/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "2.1.21"

    kotlin("kapt") version "2.1.21"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url=uri("https://jitpack.io")
    }
    maven {
        url=uri("https://central.sonatype.com/repository/maven-snapshots/")
    }
}

dependencies {
    api("org.pf4j:pf4j:${project.properties["pf4jVersion"]}")
    api("com.badlogicgames.gdx:gdx:${project.properties["libgdxVersion"]}")
    kapt("org.pf4j:pf4j:${project.properties["pf4jVersion"]}")
    api(project(":runtime"))

    implementation("com.github.jamestkhan.mundus:commons:${project.properties["mundusVersion"]}")
    implementation("com.github.jamestkhan.mundus:plugin-api:${project.properties["mundusVersion"]}")
    implementation("com.github.jamestkhan.mundus:editor-commons:${project.properties["mundusVersion"]}")

    implementation("com.github.xpenatan.xJolt:jolt-desktop:${project.properties["gdxJoltVersion"]}")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.withType<Jar> {
    dependsOn(":runtime:jar")

    archiveFileName.set("jolt-physics-plugin-${project.properties["pluginVersion"]}.jar")

    // Otherwise you'll get a "No main manifest attribute" error
    manifest {
        attributes["Plugin-Class"]= "com.github.dgzt.mundus.plugin.joltphysics.plugin.JoltPhysicsEditorPlugin"
        attributes["Plugin-Id"] = "jolt-physics-plugin"
        attributes["Plugin-Provider"] = "Tibor Zsuro (Dgzt)"
        attributes["Plugin-Version"] = "${project.properties["pluginVersion"]}"
    }

    // Include runtime in jar file
    val dependencies = configurations
        .runtimeClasspath
        .get()
        .filter {
            it.name.equals("runtime.jar") ||
            it.name.equals("jolt-core-${project.properties["gdxJoltVersion"]}.jar") ||
            it.name.equals("gdx-utils-${project.properties["gdxJoltVersion"]}.jar") ||
            it.name.equals("gdx-gl-${project.properties["gdxJoltVersion"]}.jar") ||
            it.name.equals("jolt-desktop-${project.properties["gdxJoltVersion"]}.jar") ||
            (it.name.startsWith("idl-core-") && it.name.endsWith(".jar")) ||
            (it.name.startsWith("loader-core-") && it.name.endsWith(".jar"))
        }
        .map(::zipTree)
    from(dependencies)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
